name: Vulnerable pwn request
on:
  pull_request_target:
    types: [opened, synchronize]
permissions:
  contents: write
jobs:
  privileged-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: make test
